### ISSUE TITLE
[Build] Jitpack build / config

### ISSUE THREAD

**Issue by Gounlaf** [lsxiao/Apollo#10]
Hi,

It seems that recent changes on gradle configuration make Jitpack error : https://jitpack.io/com/github/lsxiao/Apollo/18be65ac08/build.log

> org.gradle.jvmargs=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

I think it should go into a local.properties (not versioned).

Thanks for your library :)
Regards

**Comment by Sloaix** [comment]
I was not careful ,this error has since been fixed.
thx,guy :)

**Comment by Gounlaf** [comment]
Thanks for your reactivity 👍

**Comment by Sloaix** [comment]
@Gounlaf 
`1.0.0-alpha.2` is released.
The document has been updated.
