### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by zhanghuanWang** [lsxiao/Apollo#12]
如下配置,无法找到com.lsxiao.apollo.generate.ApolloBinderGeneratorImpl包,哪里出问题了,求教

 //Apollo的编译时注解处理器
  annotationProcessor "com.github.lsxiao.Apollo:processor:1.0.0-rc.3"

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://www.jitpack.io" }
    }
}

**Comment by Sloaix** [comment]
ApolloBinderGeneratorImpl类是编译时生成的，估计是没有生成成功，看看哪里报错了，或者clean一下再run一次。
![image](https://user-images.githubusercontent.com/2627625/27941894-ac28be98-6305-11e7-9ffe-0fde402a0ef0.png)


注意，@Receive修饰的方法要是public。

**Comment by zhanghuanWang** [comment]
错误大概是这样
错误: 程序包com.lsxiao.apollo.generate不存在
import com.lsxiao.apollo.generate.ApolloBinderGeneratorImpl;
                                 ^
1 个错误

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileBetaDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Sloaix** [comment]
要在gradle console才看到的编译时的报错信息。

你也可以在terminal命令行 
```sh
gradle build --stacktrace
```
看一下堆栈信息。应该是你配置有问题。

确保一定要在初始化前有Bind操作的代码，以及一个被@Receive修饰的方法的代码存在。

如果没有一个@Receive存在的话，注解处理器是没办法生成ApolloBinderGeneratorImpl的
