### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ghoulhyk** [lsxiao/Apollo#17]
compile 'io.reactivex.rxjava2:rxjava:2.1.7'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation "com.github.lsxiao.Apollo:core:1.0.1"
    annotationProcessor "com.github.lsxiao.Apollo:processor:1.0.1"

在build.gradle中添加了以上依赖，编译时报了Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: com/lsxiao/apollo/core/annotations/Receive的错误，请问应如何解决

**Comment by Sloaix** [comment]
已经在处理了，马上，是依赖的问题。不好意思。

2017-12-22 11:13 GMT+08:00 ghoulhyk <notifications@github.com>:

**Comment by Sloaix** [comment]
版本号先换成这个commit   2b6bf0ed88,我之后发一个版本。

"com.github.lsxiao.Apollo:core:2b6bf0ed88"

**Comment by ghoulhyk** [comment]
好的，多谢

**Comment by Sloaix** [comment]
版本号:1.0.1-fix
