### ISSUE TITLE
第一次使用发现，在emit上面的代码能够执行，emit后的代码不会执行

### ISSUE THREAD

**Issue by GGjin** [lsxiao/Apollo#21]
toast("修改备注成功")
 finish()
 Apollo.emit("remark", remark_edit.text.toString())

在emit前就能够finish掉Activity ，但是emit后面写finish 当前的Activity就不会被关掉，求解。

**Comment by Sloaix** [comment]
不好意思，前天公司年会，周末又比较忙，我今天排查下:)

**Comment by Sloaix** [comment]
我写了个demo排查了下，没有发现这个问题。:(，不知道你是怎么出现的。

**Comment by GGjin** [comment]
我也好奇怪 ，今天把ipc的那个依赖也加上 然后依赖到所有module里就好了。。。
