### ISSUE TITLE
代码混淆问题

### ISSUE THREAD

**Issue by JerryLocke** [lsxiao/Apollo#23]
文档中提供的混淆规则不够全面，启用 `ProGuard` 时 `ApolloBinderGeneratorImpl` 这个类也被混淆了，导致在 `Apollo.kt` 第 81 行使用反射获取这个类的 `instance` 方法时出现错误，应用崩溃。
应增加以下规则：
`-keep class com.lsxiao.apollo.generate.** { *; }`
另外，我发现英文版的文档没有提供混淆规则。

**Comment by Sloaix** [comment]
才看到这个issue,这段时间才入职，比较忙。

英文文档有点旧没更新了，我今天有空了更一下。

感谢反馈。:)
