### ISSUE TITLE
编译时没有生成绑定代码

### ISSUE THREAD

**Issue by zengjianxiong** [lsxiao/Apollo#24]
MainActivity里面
@Receive(AppConstants.RXBUS_SET_MENSTRUL_DAY_CIRCLE)
    public void updateUser(User user) {
            mainViewModel.updateUser(user);
    }
在ApolloBinderGeneratorImpl里面没有找到绑定MainActivity的代码,
但是其他类可以生成绑定代码

**Comment by Sloaix** [comment]
mBinder = Apollo.bind(this);了吗

**Comment by Sloaix** [comment]
没有问题就关闭了，可以看看之前的isuues

**Comment by zengjianxiong** [comment]
不好意思，前几天没有看到消息，我这边肯定是Apollo.bind(this)的 这个Activity 和其他的差别是里面使用databinding 我想是不是有什么冲突

**Comment by Sloaix** [comment]
有详细的gradle build日志吗

**Comment by zengjianxiong** [comment]
大佬，我抽了一个demo出来 他是mvvm+dataBinding ,我今天测试了一下单独的databinding 是可以绑定生成代码 但是加上mvvm 就不行了，希望大佬帮忙看看 这个是项目压缩包[http://omvy389id.bkt.clouddn.com/Demo.zip](url)

**Comment by Sloaix** [comment]
链接404

**Comment by zengjianxiong** [comment]
大佬 你直接复制一下链接到浏览器就可以了 http://omvy389id.bkt.clouddn.com/Demo.zip

**Comment by Sloaix** [comment]
@zengjianxiong 已修复，试试 1.0.2

**Comment by zengjianxiong** [comment]
谢谢大佬 辛苦了 现在好了
