### ISSUE TITLE
关于SubscriptionBinder绑定

### ISSUE THREAD

**Issue by oksimple** [lsxiao/Apollo#3]
你说SubscriptionBinder 可以在基类里面绑定和解绑定，为啥不直接来个默认的获取SubscriptionBinder的方法呢？ 这样我不在基类里面用就很方便啦，
比如：      EventBus.getDefault().register(......this);

因为有时候 需要在某些没有基类的地方获取消息

**Comment by oksimple** [comment]
因为编译的问题 如果第一次 直接在 Application 中初始化 会造成 SubscriberBinderImplement.instance() 未找到。。。但是干掉之后run一把 再来初始化就ok了。。。好奇怪，这是编译时生成的？

**Comment by Sloaix** [comment]
如果你想更加灵活的操作，可以调用Apollo.get().toXX方法,例如`Observable<Object> toObservable(final String tag)`,这会返回一个RxJavaObservable对象，你可以自由的进行处理,当然解除订阅也需要手动操作。
