### ISSUE TITLE
需要支持priority

### ISSUE THREAD

**Issue by Jierain** [lsxiao/Apollo#5]
高优先级的可以中断event，有很多实用场景

**Comment by Sloaix** [comment]
这段时间比较忙，月底前，我会更新版本，支持priority。

**Comment by Sloaix** [comment]
@Jierain 昨天抽时间看了下，貌似有点麻烦，我记得之前有人提过这个issue，我会尝试一下，看能不能实现，因为如果原生的RxJava Observable的订阅者不支持同步接收事件的话，就需要自己重写一遍，感觉很麻烦，且订阅者接收优先级必须是在同一线程订阅才可能实现。
