### ISSUE TITLE
Error:(14, 34) 错误: 程序包com.lsxiao.apollo.generate不存在

### ISSUE THREAD

**Issue by hekaidaqaz** [lsxiao/Apollo#6]
Error:(14, 34) 错误: 程序包com.lsxiao.apollo.generate不存在

**Comment by FENG-MASTER** [comment]
+1

**Comment by Sloaix** [comment]
注意，@Receive注解的方法一定要是public修饰的，因为不是反射，不然是调用不到的。

**Comment by FENG-MASTER** [comment]
不是public问题,这个是初始化的时候出现的 Apollo.get().init(SubscriberBinderImplement.instance(), AndroidSchedulers.mainThread()) 这句直接找不到SubscriberBinderImplement

**Comment by Sloaix** [comment]
如果Apollo.bind()后，一定要有一个被@Receive注解的方法，不然也会报这个错误
