### ISSUE TITLE
包名错误？

### ISSUE THREAD

**Issue by JerryLocke** [lsxiao/Apollo#9]
无意间发现了一个 typo，强迫症犯了，希望能够更正。
![snipaste_20170331_103221](https://cloud.githubusercontent.com/assets/5669245/24533958/944c9e02-15fd-11e7-94f1-3b45436d761c.png)

**Comment by Sloaix** [comment]
发现这个问题了。。rxjava2版本会修复
![image](https://cloud.githubusercontent.com/assets/2627625/24579153/426ccd52-1722-11e7-94b2-9b62c804e2d4.png)
